language: node_js

notifications:
    email: false

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          node_js: '7'

install:
    - npm install

script:
    - npm run build
    - ls dist/xpi
